language: cpp

sudo: required

dist: 
    - xenial

services:
    - docker

env:
    - BUILD_TYPE=Default EXEC=chrome SRC=src # TRAVIS_DEBUG_MODE=true

before_install:
    - docker pull seikwon/castanets_69_base:first
    - docker run --name castanets -dit seikwon/castanets_69_base:first /sbin/init

script:
    - docker exec -ti -e PATH=$PATH:/root/depot_tools castanets bash -c "cd ~/src && git pull && ninja -C out/Default chrome"

after_script:
    - docker stop castanets

notifications:
    email:
        recipients:
            - seikwon.kim@samsung.com
        on_success: change # <always|never|change>
        on_failure: always  # <always|never|change>

