language: cpp

sudo: required

dist: 
    - xenial

git:
    clone: false

services:
    - docker

env:
    - GIT_BRANCH=castanets_63 DOCKER_IMAGE=seikwon/castanets_69_base DOCKER_TAG=latest DOCKER_CONTAINER=castanets

before_install:
    - echo $DOCKER_IMAGE
    - echo $DOCKER_TAG
    - docker pull $DOCKER_IMAGE:$DOCKER_TAG
    - docker run --name $DOCKER_CONTAINER -dit $DOCKER_IMAGE:$DOCKER_TAG /sbin/init

before_script:
    - echo $TRAVIS_PULL_REQUEST
    - echo $TRAVIS_BRANCH
    - echo $GIT_BRANCH
    - docker exec -ti $DOCKER_CONTAINER bash -c "cd ~/src && git pull --no-edit";
    - |
        if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" = "$GIT_BRANCH" ]; then
            docker exec -ti $DOCKER_CONTAINER bash -c "cd ~/src && git pull origin refs/pull/135/head --no-edit";
        fi

script:
    - docker exec -ti -e PATH=$PATH:/root/depot_tools $DOCKER_CONTAINER bash -c "cd ~/src && ninja -C out/Default chrome";
after_script:
    - docker stop $DOCKER_CONTAINER

notifications:
    email:
        recipients:
            - seikwon.kim@samsung.com
        on_success: change # <always|never|change>
        on_failure: always  # <always|never|change>

