language: cpp

sudo: required

dist: 
    - xenial

git:
    clone: false

services:
    - docker

env:
    - BRANCH=castanets_63 BUILD_TYPE=Default EXEC=chrome SRC=src

before_install:
    - docker pull seikwon/castanets_69_base:latest
    - docker run --name castanets -dit seikwon/castanets_69_base:latest /sbin/init

before_script:
    - echo $TRAVIS_PULL_REQUEST
    - echo $TRAVIS_BRANCH
    - echo $BRANCH
    - docker exec -ti castanets bash -c "cd ~/src && git pull --no-edit";
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "$BRANCH"]; then
        docker exec -ti castanets bash -c "cd ~/src && git pull origin refs/pull/137/head --no-edit";
      fi


script:
    - docker exec -ti -e PATH=$PATH:/root/depot_tools castanets bash -c "cd ~/src && ninja -C out/Default chrome";
after_script:
    - docker stop castanets

notifications:
    email:
        recipients:
            - seikwon.kim@samsung.com
        on_success: change # <always|never|change>
        on_failure: always  # <always|never|change>

