language: cpp

sudo: required

os:
    - linux

dist: 
    - xenial

env:
    - BUILD_TYPE=Default EXEC=chrome SRC=src # TRAVIS_DEBUG_MODE=true

before_install:
    - cd ..
    - if [ ! -e depot_tools/gclient ]; then git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git; fi
    - export PATH="$PATH:$PWD/depot_tools"
    - yes | sudo add-apt-repository ppa:git-core/ppa
    - sudo apt-get update

install:
    - git clone https://github.com/Samsung/castanets ${SRC}
    - cd ${SRC}
    - yes | sudo build/install-build-deps.sh

before_script:
    - build/create_gclient.sh
    - gclient sync --with_branch_head
    - gn gen --args='enable_castanets=true enable_nacl=false is_debug=false is_component_build=true' out/${BUILD_TYPE}

script:
    - ninja -C out/${BUILD_TYPE} chrome -v
    #    - travis_wait 50 ninja -C out/${BUILD_TYPE} ${EXEC}

notifications:
    email:
        recipients:
            - seikwon.kim@samsung.com
        on_success: change # <always|never|change>
        on_failure: always  # <always|never|change>

