language: cpp

sudo: required

dist: 
    - xenial

git:
    clone: false

services:
    - docker

env:
    - BUILD_TYPE=Default EXEC=chrome SRC=src # TRAVIS_DEBUG_MODE=true

before_install:
    - docker pull seikwon/castanets_69_base:latest
    - docker run --name castanets -dit seikwon/castanets_69_base:latest /sbin/init

script:
        #docker exec -ti castanets bash -c "cd ~/src && git pull origin refs/pull/${TRAVIS_BRANCH}/head --no-edit";
    - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "TRAVIS_BRANCH" = "castanets_63"]; then
        docker exec -ti castanets bash -c "cd ~/src && git pull --no-edit";
        docker exec -ti castanets bash -c "cd ~/src && git pull origin refs/pull/135/head --no-edit";
        docker exec -ti -e PATH=$PATH:/root/depot_tools castanets bash -c "cd ~/src && ninja -C out/Default chrome";
      fi
after_script:
    - docker stop castanets

notifications:
    email:
        recipients:
            - seikwon.kim@samsung.com
        on_success: change # <always|never|change>
        on_failure: always  # <always|never|change>

