
step-generate-castanets-build-args: &step-generate-castanets-build-args
    run:
        name: Set build argument for Castanets
        command: |
            cd src 
            #$SRC
            gn gen --args='enable_castanets=true enable_nacl=false is_debug=false is_component_build=true' out/Default 
            #$BUILD_TYPE

step-castanets-build: &step-castanets-build
    run:
        name: Ninja build Castanets
        no_output_timeout: 2h
        command: |
            cd src 
            #$SRC
            ninja -C out/Default chrome 
            #${BUILD_TYPE} ${EXEC}

step-update-git: &step-update-git
    run:
        name: Update Git Repo
        command: |
            cd ~/src
            git pull --no-edit

step-merge-pull-request: &step-merge-pull-request
    run:
        name: Merge Pull request
        command: |
            if [ "$CIRCLE_PR_NUMBER" != "false" ] && [ "$CIRCLE_BRANCH" = "castanets_63" ]; then
                cd ~/src && git pull origin refs/pull/137/head --no-edit
            else
                echo "$CIRCLE_PR_NUMBER" && echo "$CIRCLE_BRANCH"
            fi

step-build-image: &step-build-image
    run:
        name: Build image
        command: |
            cd ~/src && ninja -C out/Default chrome


# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
    build: 
        docker:
            - image: seikwon/castanets_69_base
    
        steps:
            - *step-update-git
            - *step-merge-pull-request
            - *step-build-image
